#!/bin/python3
import random 
chars = 'abcdefghijklmnopqrstuvwxyz1234567890!?.,-'
number = input('number of passwords?')
number = int(number)
length = input('password length?')
length = int(length)
for p in range(number):
  password = ''
  for c in range(length):
    password += random.choice(chars)
  print (password)
  
---------------------------------

number of passwords? 7
password length? 5
7y9r?
ebzfs
zircc
l5n7n
vogh-
,eo0s
a6yyp


number of passwords? 3
password length? 4
!j9n
mu-m
0pix
